# :D
print ('Як тебе звати?')
name=input()
print ('Дороу, ' +name)
print ('Скільки тобі років?')
age=input()
print ('Клас! ' +age, 'найкращий вік!')
print ('Де ти живеш?')
city=input()
print ('Вау, ' +city, 'то дуже гарне місто!')

#згідно умов домашки
print ('What is your name?')
name=input()
print ('How old are you?')
age=input()
print ('Where do you live?')
city=input()
print ('Hello, '+name)
print ('Your age is '+age)
print ('You live in '+city)
